const ACTIONS = {
  // user
  USER_LOADING: "USER_LOADING",
  ADD_USER: "ADD_USER",
  SET_CURRENT_USER: "SET_CURRENT_USER",
  // availability
  AVAILABILITY_LOADING: "AVAILABILITY_LOADING",
  ADD_AVAILABILITY: "ADD_AVAILABILITY",
  // friendship
  FRIENDSHIP_LOADING: "FRIENDSHIP_LOADING",
  ADD_FRIENDSHIP: "ADD_FRIENDSHIP",
  // hangtime
  HANGTIME_LOADING: "HANGTIME_LOADING",
  ADD_HANGTIME: "ADD_HANGTIME",
};

export default ACTIONS;
