const ACTIONS = {
  // user
  USER_LOADING: "USER_LOADING",
  ADD_USER: "ADD_USER",
  SET_CURRENT_USER: "SET_CURRENT_USER",
  // availability
  AVAILABILITY_LOADING: "AVAILABILITY_LOADING",
  ADD_AVAILABILITY: "ADD_AVAILABILITY",
  // friendship
  // hangtime
};

export default ACTIONS;
